### ISSUE TITLE
[Documentation] Unclear scope of "all apps"

### ISSUE THREAD

**Issue by Olf0** [sailfishos/sailjail-permissions#126]
The fourth sentence of [the Sailjail README](https://github.com/sailfishos/sailjail-permissions/tree/6a79d43b20b1fcd70d7c4d56bf63fde574c91af5#readme) currently states: "Target is to have application sandboxing enforced to all applications, starting from Sailfish OS 4.4.0."

* I wonder what "all" is supposed to mean precisely:
  1. … enforced for all applications by Jolla, …
  2. … enforced for all applications available at the Jolla Store ("harbour"), …
  3. … enforced for every application installed, …
  
  Please clarify the wording in the README, e.g., with one of my suggestions.

* Jolla obviously missed the goal of reaching this target by Sailfish OS 4.4.0.  AFAIU the Jolla Store app is not sandboxed, yet.
   While missing due dates is quite common in the IT-business, you might want to update the Sailfish OS release version in this sentence with your current target release.

**Comment by llewelld** [comment]
I'm not a sandboxing guru so someone may come along and correct me. However, my understanding of the suggestion to "have application sandboxing enforced to all applications" ¹  is that it meant any app that *doesn't* have either permissions or an opt-out specified, will be sandboxed by default anyway. This change was introduced in the  4.4.0 release.

Given this, and also given that the readme is now talking about an event in the past, maybe a better wording would be something like (just an initial suggestion):

"Since Sailfish OS 4.4.0 all applications that do not specifically opt-out or define permissions are sandboxed automatically using a default profile."

¹ <sub>This was also described in @vigejolla's [sandboxing blog post](https://blog.jolla.com/whats-up-with-sandboxing/) as "we are planning to eventually sandbox all Sailfish apps by default".</sub>

**Comment by llewelld** [comment]
Here's that proposal in PR form: https://github.com/sailfishos/sailjail-permissions/pull/128
